dist: xenial
sudo: required

language: c
compiler:
  - gcc
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libcap-dev libgtest-dev cmake libsndfile1-dev libboost-all-dev libtbb-dev graphviz libtool m4 automake libdbus-1-dev libpci-dev linux-headers-generic libsystemd-dev

script: ./travis.sh
